# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
  #  - ur5e_arm_gripper_controller
    - ur5e_arm_controller
    - gripper_controller

  
  ur5e_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  gripper_controller:
    type: GripperCommand
    joints:
      - finger_joint
    action_ns: gripper_cmd
    default: true